// import {
//   profile,
//   user1,
//   user2,
//   user3,
//   user4,
//   user5,
//   user6,
//   user7,
//   user8,
//   user9,
// } from "../assets/images/userImages/";

import { Image } from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from "react-native-responsive-screen";

export const userData = [
  {
    id: 9,
    name: "Peggie",
    age: 28,
    hobbies: ["Concerts", "Festivals", "Photography"],
    bio: "Hey there! My name is Peggie. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life. When I'm not behind the lens, you'll find me immersing myself in the energy of live music at concerts and festivals. Exploring new cultures and cuisines is my idea of a perfect adventure. Let's share stories over a cup of coffee and see where our shared passions take us!",
    distance: "3 miles away",
    imgPath: 'https://i.pinimg.com/originals/82/ec/a2/82eca2d04cc1f455b330b64a45272445.jpg',
  },
  {
    id: 4,
    name: "Ella",
    age: 28,
    hobbies: ["Concerts", "Festivals", "Photography"],
    bio: "Hey there! My name is Ella. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life. When I'm not behind the lens, you'll find me immersing myself in the energy of live music at concerts and festivals. Exploring new cultures and cuisines is my idea of a perfect adventure. Let's share stories over a cup of coffee and see where our shared passions take us!",
    distance: "3 miles away",
    imgPath: 'https://i.pinimg.com/736x/c6/c0/63/c6c063ec1e5f47cfe473b250f3a950e0.jpg',
  },
  {
    id: 1,
    name: "Diana",
    age: 30,
    hobbies: ["Hiking", "Cooking", "Music"],
    bio: "Hi there! I'm Diana, a nature lover who finds joy in the kitchen and the magic of music. Let's go on a hike and then cook up a storm together. Seeking someone to share adventures and good food with.",
    distance: "10 miles away",
    imgPath: 'https://images4.alphacoders.com/117/1179786.jpg',
  },
  {
    id: 8,
    name: "Sophie",
    age: 26,
    hobbies: ["Painting", "Yoga", "Traveling"],
    bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar. Let's embark on a journey of self-discovery together, exploring the world and creating masterpieces along the way.",
    distance: "2 miles away",
    imgPath: 'https://i.pinimg.com/originals/d1/ea/b2/d1eab22e96242eb259aac30aaf85af5e.jpg',
  },
  {
    id: 11,
    name: "Betty",
    age: 32,
    hobbies: ["Soccer", "Cooking", "Movies"],
    bio: "Hi there! I'm Betty, a soccer lover who finds joy in the kitchen and the magic of movies. Let's kick a ball around and then cook up a storm together. Seeking someone to share adventures and good food with.",
    distance: "5 miles away",
    imgPath: 'https://s-media-cache-ec0.pinimg.com/736x/38/fa/f4/38faf4376d7bf8ae30b902b2ff606afb.jpg',
  },
  {
    id: 12,
    name: "Lily",
    age: 29,
    hobbies: ["Dancing", "Reading", "Hiking"],
    bio: "Hola! I'm Lily, a dance lover who finds joy in the rhythm of life. Books are my escape, and hiking fuels my spirit. Let's dance under the stars and get lost in stories over a cup of coffee. Eager to meet someone to share life's dance with.",
    distance: "7 miles away",
    imgPath: 'https://hottestchocolate.com/wp-content/uploads/2022/05/Yael_Shelbia_5.jpg',
  },
  {
    id: 3,
    name: "Chiara",
    age: 28,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Ciao! I'm Chiara, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: 'https://th.bing.com/th/id/R.9fee440931fcc4e27c1dc882f94c733a?rik=b8hMbaPki6fNUA&pid=ImgRaw&r=0',
  },
  {
    id: 13,
    name: "Emma",
    age: 27,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Hi there! I'm Emma, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: 'https://ilarge.lisimg.com/image/16790599/740full-polina-kostyuk.jpg',
  },
  {
    id: 2,
    name: "Jane",
    age: 27,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Hi there! I'm Jane, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: 'https://th.bing.com/th/id/R.719b32a872c945c8471946818c4dd620?rik=maKgd5bXuW3Fjg&riu=http%3a%2f%2fthewowstyle.com%2fwp-content%2fuploads%2f2015%2f05%2fpictures-of-beautiful-women1.jpg&ehk=MSzVcZlb%2bvzTkicxjQY0I2zEkkkjh43a4gg6Q3cL3GU%3d&risl=&pid=ImgRaw&r=0' ,
  },
  {
    id: 5,
    name: "Julie",
    age: 27,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Hi there! I'm Julie, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: 'https://www.goodfreephotos.com/albums/people/beautiful-women-in-white-dress.jpg',
  },
  {
    id: 14,
    name: "Sarah",
    age: 29,
    hobbies: ["Surfing", "Gardening", "Painting"],
    bio: "Hi there! I'm Sarah, a surfer who finds joy in the garden and the magic of painting. Let's ride the waves and then paint up a storm together. Seeking someone to share adventures and good food with.",
    distance: "8 miles away",
    imgPath: 'https://static1.squarespace.com/static/53e0226ae4b0e8abaa8ad2af/t/5b95ef0c352f531880e11221/1536552730513/',
  },
  {
    id: 6,
    name: "Olivia",
    age: 28,
    hobbies: ["Yoga", "Hiking", "Photography"],
    bio: "Hello, I'm Olivia, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
    distance: "9 miles away",
    imgPath: 'https://i.pinimg.com/originals/89/ed/bb/89edbb14abe20159eea5bea47ea249d9.jpg',
  },
  {
    id: 10,
    name: "Alex",
    age: 28,
    hobbies: ["Yoga", "Hiking", "Photography"],
    bio: "Hello, I'm Alex, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
    distance: "9 miles away",
    imgPath: 'https://i.pinimg.com/originals/0a/93/5a/0a935af5ef8383b82039b29790e35505.jpg',
  },
  {
    id: 7,
    name: "William",
    age: 28,
    hobbies: ["Yoga", "Hiking", "Photography"],
    bio: "Hello, I'm William, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
    distance: "9 miles away",
    imgPath: 'https://i.pinimg.com/originals/32/85/6c/32856c9c423d0177314604cbf46cd3cb.jpg',
  },
];

export const chatData = [
  {
    id: 1,
    name: "Betty",
    imgUrl: '../assets/images/userImages/user1',
    age: 32,
    isOnline: true,
    lastMessage:
      "That sounds like a lot of fun. Would you like to go together sometime?",
    date: "2023-10-15",
    timeSent: "5 mins",
    chat: [
      {
        sender: "me",
        message: "Hi there! How's it going?",
        timestamp: "10:00 AM",
      },
      {
        sender: "Betty",
        message: "I am doing great, thanks!",
        timestamp: "10:05 AM",
      },
      {
        sender: "me",
        message: "Have any exciting plans for the weekend? 😊",
        timestamp: "10:10 AM",
      },
      {
        sender: "Betty",
        message: "Yes, I'm thinking of going hiking. 🏞️ What about you?",
        timestamp: "10:15 AM",
      },
      {
        sender: "me",
        message: "That sounds amazing! I might just tag along. 🥾",
        timestamp: "10:20 AM",
      },
      {
        sender: "Betty",
        message: "That would be great! The more, the merrier. 🌟",
        timestamp: "10:25 AM",
      },
    ],
  },
  {
    id: 2,
    name: "Basquit",
    imgUrl: '../assets/images/userImages/user2',
    age: 28,
    isOnline: false,
    lastMessage: "Sure, let's do that. When are you free?",
    date: "2023-10-14",
    timeSent: "10 mins",
    chat: [
      {
        sender: "me",
        message: "Hey Charlie, how have you been?",
        timestamp: "11:00 AM",
      },
      {
        sender: "Charlie",
        message: "I've been good. How about you?",
        timestamp: "11:05 AM",
      },
      {
        sender: "me",
        message: "I've been a bit busy, but managing. 😊",
        timestamp: "11:10 AM",
      },
      {
        sender: "Charlie",
        message: "I understand. We should catch up soon! ☕",
        timestamp: "11:15 AM",
      },
      {
        sender: "me",
        message: "Definitely! Let's plan something for this weekend. 🎉",
        timestamp: "11:20 AM",
      },
      {
        sender: "Charlie",
        message: "Sure, that sounds good. When are you free? 🗓️",
        timestamp: "11:25 AM",
      },
      {
        sender: "me",
        message: "I'm free on Saturday afternoon. How about you? 🌤️",
        timestamp: "11:30 AM",
      },
      {
        sender: "Charlie",
        message: "Saturday works for me too! Let's meet at our usual spot. 🍔",
        timestamp: "11:35 AM",
      },
      {
        sender: "me",
        message: "Sounds like a plan! See you then. 👋",
        timestamp: "11:40 AM",
      },
    ],
  },
  {
    id: 3,
    name: "Oliver",
    imgUrl: '../assets/images/userImages/user3',
    age: 30,
    isOnline: true,
    lastMessage: "Sounds like a plan! Let's make it happen.",
    date: "2023-10-11",
    timeSent: "25 mins",
    chat: [
      {
        sender: "me",
        message: "Hi Oliver, how's your day going?",
        timestamp: "2:00 PM",
      },
      {
        sender: "Oliver",
        message: "It's going great! Enjoying the sunshine. How about you?",
        timestamp: "2:05 PM",
      },
      {
        sender: "me",
        message: "That's wonderful! I'm just getting through some work. 💻",
        timestamp: "2:10 PM",
      },
      {
        sender: "Oliver",
        message: "Don't work too hard! Make sure to take breaks. 🌞",
        timestamp: "2:15 PM",
      },
      {
        sender: "me",
        message:
          "Absolutely, breaks are necessary. Planning anything fun for the evening? 🎉",
        timestamp: "2:20 PM",
      },
      {
        sender: "Oliver",
        message: "I might go to the gym later. Need to work off some steam. 💪",
        timestamp: "2:25 PM",
      },
      {
        sender: "me",
        message: "That's a great idea! I should join you sometime. 🏋️‍♂️",
        timestamp: "2:30 PM",
      },
      {
        sender: "Oliver",
        message: "Definitely! The more, the merrier. 🤸‍♂️",
        timestamp: "2:35 PM",
      },
    ],
  },
  {
    id: 4,
    name: "Sophie",
    imgUrl: '../assets/images/userImages/user9',
    age: 27,
    isOnline: true,
    lastMessage: "Definitely! Looking forward to it.",
    date: "2023-10-10",
    timeSent: "30 mins",
    chat: [
      {
        sender: "me",
        message: "Hey Sophie, how's your week been?",
        timestamp: "3:00 PM",
      },

      {
        sender: "Sophie",
        message: "It's been busy but good. How about you?",
        timestamp: "3:05 PM",
      },
      {
        sender: "Sophie",
        message: "And also tired",
        timestamp: "3:05 PM",
      },
      {
        sender: "me",
        message: "Mine's been quite hectic too, but managing.",
        timestamp: "3:10 PM",
      },
      {
        sender: "Sophie",
        message: "That's good to hear. Any exciting plans for the weekend?",
        timestamp: "3:15 PM",
      },
      {
        sender: "me",
        message:
          "Not yet, but I'm thinking of checking out that new restaurant downtown. You?",
        timestamp: "3:20 PM",
      },
      {
        sender: "Sophie",
        message:
          "I'm planning to go hiking with some friends. You should join us sometime!",
        timestamp: "3:25 PM",
      },
    ],
  },

  {
    id: 5,
    name: "William",
    imgUrl:'../assets/images/userImages/user1',
    age: 29,
    isOnline: false,
    lastMessage: "Let me check my schedule and get back to you.",
    date: "2023-10-09",
    timeSent: "35 mins",
    chat: [
      {
        sender: "me",
        message: "Hi William, how's everything going?",
        timestamp: "4:00 PM",
      },
      {
        sender: "William",
        message: "Things are going well. How about you?",
        timestamp: "4:05 PM",
      },
    ],
  },
  {
    id: 6,
    name: "Jack",
    imgUrl: '../assets/images/userImages/user3',
    age: 30,
    isOnline: true,
    lastMessage: "Sounds like a great idea. Let's make it happen.",
    date: "2023-10-07",
    timeSent: "45 mins",
    chat: [
      {
        sender: "me",
        message: "Hey Jack, how's your week been?",
        timestamp: "6:00 PM",
      },
      {
        sender: "Jack",
        message: "It's been busy but good. How about you?",
        timestamp: "6:05 PM",
      },
    ],
  },
];

export const datesData = [
  {
    id: 1,
    imgUrl: 'https://images4.alphacoders.com/117/1179786.jpg',
    name: "Dianna",
    lastName: "Jones",
    age: 25,
    city: "New York",
    country: "USA",
    gender: 'female',
  },
  {
    id: 2,
    imgUrl: 'https://th.bing.com/th/id/R.719b32a872c945c8471946818c4dd620?rik=maKgd5bXuW3Fjg&riu=http%3a%2f%2fthewowstyle.com%2fwp-content%2fuploads%2f2015%2f05%2fpictures-of-beautiful-women1.jpg&ehk=MSzVcZlb%2bvzTkicxjQY0I2zEkkkjh43a4gg6Q3cL3GU%3d&risl=&pid=ImgRaw&r=0',
    name: "Jane",
    lastName: "Smith",
    age: 28,
    city: "Los Angeles",
    country: "USA",
    gender: 'female',
  },
  {
    id: 3,
    imgUrl: 'https://th.bing.com/th/id/R.9fee440931fcc4e27c1dc882f94c733a?rik=b8hMbaPki6fNUA&pid=ImgRaw&r=0',
    name: "Chiara",
    lastName: "Doe",
    age: 26,
    city: "London",
    country: "UK",
    gender: 'female',
  },
  {
    id: 4,
    imgUrl: 'https://i.pinimg.com/736x/c6/c0/63/c6c063ec1e5f47cfe473b250f3a950e0.jpg',
    name: "Ella",
    lastName: "Williams",
    age: 29,
    city: "Sydney",
    country: "Australia",
    gender: 'female',
  },
  {
    id: 5,
    imgUrl: 'https://www.goodfreephotos.com/albums/people/beautiful-women-in-white-dress.jpg',
    name: "Jullie",
    lastName: "Brown",
    age: 30,
    city: "Paris",
    country: "France",
    gender: 'female',
  },
  {
    id: 6,
    imgUrl: 'https://i.pinimg.com/originals/89/ed/bb/89edbb14abe20159eea5bea47ea249d9.jpg',
    name: "Olivia",
    lastName: "Miller",
    age: 27,
    city: "Berlin",
    country: "Germany",
    gender: 'female',
  },
  {
    id: 7,
    imgUrl: 'https://i.pinimg.com/originals/32/85/6c/32856c9c423d0177314604cbf46cd3cb.jpg',
    name: "William",
    lastName: "Wilson",
    age: 31,
    city: "Toronto",
    country: "Canada",
    gender: 'male',
  },
  {
    id: 8,
    imgUrl: 'https://i.pinimg.com/originals/d1/ea/b2/d1eab22e96242eb259aac30aaf85af5e.jpg',
    name: "Sophia",
    lastName: "Moore",
    age: 29,
    city: "Tokyo",
    country: "Japan",
    gender: 'female',
  },
  {
    id: 9,
    imgUrl: 'https://i.pinimg.com/originals/82/ec/a2/82eca2d04cc1f455b330b64a45272445.jpg',
    name: "Peggie",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
    gender: 'female',
  },
  {
    id: 11,
    imgUrl: 'https://s-media-cache-ec0.pinimg.com/736x/38/fa/f4/38faf4376d7bf8ae30b902b2ff606afb.jpg',
    name: "Betty",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
    gender: 'female',
  },
  {
    id: 12,
    imgUrl: 'https://hottestchocolate.com/wp-content/uploads/2022/05/Yael_Shelbia_5.jpg',
    name: "Lilly",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
    gender: 'female',
  },
  {
    id: 13,
    imgUrl: 'https://ilarge.lisimg.com/image/16790599/740full-polina-kostyuk.jpg',
    name: "Emma",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
    gender: 'female',
  },
  {
    id: 14,
    imgUrl: 'https://static1.squarespace.com/static/53e0226ae4b0e8abaa8ad2af/t/5b95ef0c352f531880e11221/1536552730513/',
    name: "Sarah",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
    gender: 'female',
  },
  {
    id: 10,
    imgUrl: 'https://i.pinimg.com/originals/0a/93/5a/0a935af5ef8383b82039b29790e35505.jpg',
    name: "Alex",
    lastName: "Anderson",
    age: 30,
    city: "Moscow",
    country: "Russia",
    gender: 'male',
  },
];

export const profileData = [
  {
    name: "Jacob Jones",
    age: 30,
    imgUrl: '../assets/images/userImages/user1.jpg',
    hobbies: ["Hiking", "Photography", "Cooking"],
    bio: "I'm an adventurous person who loves exploring new places, trying out different cuisines, capturing moments through photography, and spending time in nature. I enjoy hiking on weekends and experimenting with new recipes in the kitchen. Traveling and experiencing different cultures are some of my greatest passions, and I'm always looking for my next adventure.",
    gender: 'male',
  },
];
